### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by idkjs** [pckilgore/reason-cognito#1]
I would not mind helping on this. I have messed with these types for a while now and been meaning to do something with them. Looking for them now...

**Comment by pckilgore** [comment]
I have aws amplify/auth pretty well typed by now on a few projects, but it leaves a lot to be desired, especially error handling.  Holler if you want to compare notes, but I largely gave up doing a really good job there because the error handling is a fucking mess in that library with all sorts of different error shapes.  Then there's the fact that library is inexcusably large (IMO) for what it does...

My goal here was to build a low level lib to talk directly to the cognito REST endpoints using reason from request to response.

If those were working well, I was going to try to use them as primatives to build something amplify/auth -like for my reason-react projects (local storage of tokens, caching, etc.).

And I needed something that was complex enough it would force me to really use reason well, but a problem domain that I understood really well.

Do we align there?  I think the community would really benefit from good typings on top of the cognito SDK, but this project might not be it?

**Comment by idkjs** [comment]
I'm all in, man, if you want to guide the way. I'm a kind of stare at it until I see the pattern type dude and I have stared at aws alot.  I hear you on the callbacks and what not. Its a mess. You end up resorting to just the thing that works for the moment. But working on something like this would really help me to understand what I am dealing with and also to learn from someone who has a clue. So what do we do? Set up some goals and get at it?

**Comment by pckilgore** [comment]
I know about cognito but not much about ReasonML library architecture lol.
I'll dump a checklist up somewhere.

Step one is find a good reason http fetch/xmlhttp client that, ideally,
exposes a callbag or monadic api ideally we don't make people deal with
promises...

**Comment by idkjs** [comment]
All kinds of solutions for that from what I can tell. Here is a demo in the standard ocaml http. https://github.com/mirage/ocaml-cohttp/blob/master/examples/async/s3_cp.ml.

I'm so used to using graphql, or bs-fetch, that i have not really though about dealing with http too much. Is the idea to have a client the library that hits the endpoints?

These guys just dropped a thing. https://github.com/reason-native-web/morph

**Comment by pckilgore** [comment]
Sooooo, the rest endpoint I was reading up on is the one they implement for third-party oauth.   What I really **need** are the docs for the cognito-idp endpoint.  I don't really feel like reverse engineering one of the open-source client libraries for that (it's not impossible, but *I ain't got time for that*).  So that is a bit of a blocker for my original goals.

I always figured the `amazon-cognito-identity-js` library would be just as hard to wrap as amplify/auth, but just be less useful as it is way lower level.   I guess I'm going to play around with that a little bit today and see what shakes out.

**Comment by idkjs** [comment]
this guy seems to have done some work on it https://github.com/aws-samples/amazon-cognito-example-for-external-idp.

Is this what you are referring to https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/index.html?

**Comment by pckilgore** [comment]
Nah, my thought was to to build something around the
https://cognitp-idp.REGION.amazonaws.com endpoint.  It's what Amazon's
libraries talk to.  It's just so object-oriented in amazon library land
that I'd prefer to avoid building a wrapper of their libraries and variadic
method calls and implied state.

**Comment by idkjs** [comment]
ok, brother. Whatever you want to do is good with me. I am along for the ride.

**Comment by pckilgore** [comment]
https://github.com/pckilgore/reason-cognito/blob/b9a14f7c9a24d7b7326b077164f83df937bd350c/src/Client.re#L43-L92

This API feels decent.  Thoughts?  Obviously room for improvement.

If we can standardize around even a rough pattern I could really use help reverse engineering the rest of the calls from https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js

**Comment by pckilgore** [comment]
It's not really that awful.  You concat an operating name onto a header that governs what they get back to you.  There's some extra security stuff that I'm only eying suspiciously at this point.  You have to pay for it extra in cognito and I've never bothered at home or at work so I'm not really sure what it gets you.

**Comment by pckilgore** [comment]
My dream is to be able to do:

```reason
Cognito.signUp("user", "pass", attributes, validation)
 -> Future.mapOk(responseType -> /* do stuff */)
 -> Future.mapError(err -> switch(err) {
      | NetworkError =>  /* stuff */
      | AmazonErrorHere => /* stuff */
   })
``
No more Js.Promise cruft littering react components.

**Comment by idkjs** [comment]
Looks good to me. My philosophy is to run it until we break something and fix it. Looks good just looking at it. I will look at the reverse engineering the calls asap. As far as cognito goes, i'm pretty sure it just dumps all the data on you every time you call then you parse it how of it what you want.I know that is what amplify does. I wonder what effect that has on performance? Do we have to get the whole data dump every time? Must be a way to only get some pieces of info instead of sending everything back to the client. 

I know I have the reverse engineering done from back when I knew nothing. It  will be good to revisit now that I have a bit of clue. Tight work, sir. I will get at it tomorrow.

**Comment by pckilgore** [comment]
https://github.com/pckilgore/reason-cognito/tree/dev

<-- Signup in a not-awful API.  Will need some sort of partially applied module (I forget the real name for it...) to keep the basic setup around in closure.  It really is a poor mans object (and vice versa...).

Feel free to add users at will there.  If you get further into this I can cut you some IAM credentials to access that user pool to debug stuff.

**Comment by idkjs** [comment]
We should set up a time to pair program one of these modules so we I can get on the same page with some of wht you are doing here. Are you open to doing that?

**Comment by pckilgore** [comment]
My DX with several bindings has been really awful.  They are just as opinionated as a separate library about their abstractions, but provide none of the potential benefits of a rewrite, and lots of downsides (OOP design that assumes state and doesn't map well to a functional style, throwing JS exceptions, messy union return types on top of messy promises. 

So yeah, the goal here is to try to do it from scratch, The Right Way.  I understand the downsides to this, but 80% of any side project I start is so that *I* can learn something, results be damned.  

That said, yeah, totally open to pairing.  I'm US CT if that matters.  I want to get sign up and sign in working and be _really_ happy with the API exposed.  Once that feels right, I/we can go port the rest (resetPassword, logout, etc.).  Once those low level primitives are done, maybe here, maybe separately, I'd also like to integrate local credential storage and automatic token refresh.  And if I'm feeling _really_ ambitious, export a react hooks API to make this all as trivial as possible for people to use in Reason-React.

**Comment by pckilgore** [comment]
My DX with several bindings has been really awful.  They are just as opinionated as a separate library about their abstractions, but provide none of the potential benefits of a rewrite, and lots of downsides (OOP design that assumes state and doesn't map well to a functional style, throwing JS exceptions, messy union return types on top of messy promises. 

So yeah, the goal here is to try to do it from scratch, The Right Way.  I understand the downsides to this, but 80% of any side project I start is so that *I* can learn something, results be damned.  

That said, yeah, totally open to pairing.  I'm US CT if that matters.  I want to get sign up and sign in working and be _really_ happy with the API exposed.  Once that feels right, I/we can go port the rest (resetPassword, logout, etc.).  Once those low level primitives are done, maybe here, maybe separately, I'd also like to integrate local credential storage and automatic token refresh.  And if I'm feeling _really_ ambitious, export a react hooks API to make this all as trivial as possible for people to use in Reason-React.

But I just got pointed towards polymorphic variants on twitter, so I'm going to look into that, because the error type of my local branch is starting to be monstrous and could really benefit from some composition: https://keleshev.com/composable-error-handling-in-ocaml

**Comment by pckilgore** [comment]
Why github does not put close and comment behind a confirmation continues to blow my mind.

**Comment by idkjs** [comment]
lol. I have signup, confirmSignup working. Try to get access to a usersession most of the afternoon. Missing something about how to call it. The api seems to have a bunch of stuff marked private. Should we not be using those functions? I need to do a push real quick so you can see see it. Also, what do you have the `AuthFlow` configured to be?

Getting this when trying to get the session token:

```reason
Raw Response { __type: 'UnknownOperationException' }
➜  reason-cognito-dev2 node src/client-actions/InitiatingAuth.bs.js
userNameObj { USERNAME: 'idkjs' }
Raw Response {
  __type: 'UnexpectedLambdaException',
  message: 'null invocation failed due to configuration.'
}
```

Totally agree on the side project philosophy. That is why i am right here with you grinding through this foolishness!

**Comment by idkjs** [comment]
Need tokens, boss? Are we getting one back from signup? Do we need to implement storage?

Came across this while looking for answers these questions....https://github.com/ulrikstrid/reason-oidc-provider

**Comment by pckilgore** [comment]
> The api seems to have a bunch of stuff marked private. Should we not be using those functions? 
Can you link me to the equivalent code [in the JS SDK](https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js), I'm not sure what kind of private this means.

> what do you have the AuthFlow configured to be?

I haven't gotten far enough to care yet, because I'm on a side quest around error API and configuration API design.  But we can do this in stages.  USER_PASSWORD_AUTH flow might be the easiest place to start, no tokens, straight forward, a bit not secure although https means it's not AWFUL.

I did forget to allow USER_PASSWORD flow, though, so I just turned that on.

![image](https://user-images.githubusercontent.com/2559043/65817863-c4f02e00-e1d1-11e9-9b97-ec838dfb4c20.png)

You have keybase?  Happy to cut you IAM credentials and send them over so you can turn knobs on my test endpoint.  Or I am pretty sure cognito is part of AWS free tier, so you can always just set up your own.

> Need tokens, boss? Are we getting one back from signup?

Eventually we will need to be able to handle the entire SRP dance, including passing and parsing JWT as part of the signIn flow.  We definitely were being forced into that flow until I just changed those settings a few minutes ago.  Nice to know that someone's already taken a hack at OIDC stuff, looks like that's server code, I'll bookmark it for mining later, but it doesn't look licensed, so I want to be careful about that for now.

> Do we need to implement storage?
Implementing feels a bit YAGNI right now, but who knows, it might be essential to implement token refresh.  It's definitely on the roadmap.

**Comment by idkjs** [comment]
On `YAGNI`, i get it. Had to look it up, but I follow. This is my first time collaborating to so please be patient with my questions. Some of will sound like and actually be thinking out loud. It helps.

Having said that, your setting `USER_PASSWORD_AUTH` gave me something to work with and signing in is now working. check this commit https://github.com/pckilgore/reason-cognito/pull/2/commits/47bfaf88ef2e24b3b3fa9180101665e44071cdd8

Looking forward to your learning on error handling.

**Comment by pckilgore** [comment]
> On `YAGNI`, i get it. Had to look it up, but I follow. This is my first time collaborating to so please be patient with my questions. Some of will sound like and actually be thinking out loud. It helps.

Sorry, work jargon leaking, lol.  I do appreciate any and all thoughts!  

>  Having said that, your setting USER_PASSWORD_AUTH gave me something to work with and signing in is now working. check this commit 47bfaf8

Will do, because...

> Looking forward to your learning on error handling.

It's done! f1b437a8eaafd19abafae9443069537bbce03ec0

I'm going to close this issue since we're making decent progress, please feel free to continue any discussion you want a more scoped issue so I can sort it all out mentally and keep a good record of decisions made (like me talking to myself on #3, lol).
